name: binder_env
channels:
- defaults
dependencies:
- asn1crypto=0.24.0=py36_0
- babel=2.5.3=py36_0
- backcall=0.1.0=py36_0
- backports=1.0=py36h81696a8_1
- backports.weakref=1.0rc1=py36_0
- bleach=1.5.0=py36_0
- ca-certificates=2018.03.07=0
- certifi=2018.1.18=py36_0
- cffi=1.11.5=py36h945400d_0
- chardet=3.0.4=py36h420ce6e_1
- colorama=0.3.9=py36h029ae33_0
- cryptography=2.2.2=py36hfa6e2cd_0
- decorator=4.3.0=py36_0
- docutils=0.14=py36h6012d8f_0
- html5lib=0.9999999=py36_0
- icc_rt=2017.0.4=h97af966_0
- idna=2.6=py36h148d497_1
- imagesize=1.0.0=py36_0
- intel-openmp=2018.0.0=8
- ipykernel=4.8.2=py36_0
- ipython=6.3.1=py36_0
- ipython_genutils=0.2.0=py36h3c5d0ee_0
- jedi=0.12.0=py36_0
- jinja2=2.10=py36h292fed1_0
- jupyter_client=5.2.3=py36_0
- jupyter_core=4.4.0=py36h56e9d50_0
- libprotobuf=3.5.2=he0781b1_0
- markdown=2.6.11=py36_0
- markupsafe=1.0=py36h0e26971_1
- mkl=2018.0.2=1
- mkl_fft=1.0.1=py36h452e1ab_0
- mkl_random=1.0.1=py36h9258bd6_0
- numpy=1.14.2=py36h5c71026_1
- numpydoc=0.8.0=py36_0
- openssl=1.0.2o=h8ea7d77_0
- packaging=17.1=py36_0
- pandas=0.22.0=py36h6538335_0
- parso=0.2.0=py36_0
- pickleshare=0.7.4=py36h9de030f_0
- pip=9.0.3=py36_0
- prompt_toolkit=1.0.15=py36h60b8f86_0
- protobuf=3.5.2=py36h6538335_0
- pycparser=2.18=py36hd053e01_1
- pygments=2.2.0=py36hb010967_0
- pyopenssl=17.5.0=py36h5b7d817_0
- pyparsing=2.2.0=py36h785a196_1
- pysocks=1.6.8=py36_0
- python=3.6.5=h0c2934d_0
- python-dateutil=2.7.2=py36_0
- pytz=2018.4=py36_0
- pyzmq=17.0.0=py36hfa6e2cd_0
- requests=2.18.4=py36h4371aae_1
- setuptools=39.0.1=py36_0
- simplegeneric=0.8.1=py36_2
- six=1.11.0=py36h4db2310_1
- snowballstemmer=1.2.1=py36h763602f_0
- sphinx=1.7.2=py36_0
- sphinxcontrib=1.0=py36hbbac3d2_1
- sphinxcontrib-websupport=1.0.1=py36hb5e5916_1
- tensorflow=1.2.1=py36_0
- tornado=5.0.1=py36_1
- traitlets=4.3.2=py36h096827d_0
- typing=3.6.4=py36_0
- urllib3=1.22=py36h276f60a_0
- vc=14=h0510ff6_3
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py36h3d5aa90_0
- werkzeug=0.14.1=py36_0
- wheel=0.31.0=py36_0
- win_inet_pton=1.0.1=py36he67d7fd_1
- wincertstore=0.2=py36h7fe50ca_0
- zlib=1.2.11=h8395fce_2
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-core==4.4.0
  - mkl-fft==1.0.0
  - mkl-random==1.0.1
  - prompt-toolkit==1.0.15
  - win-inet-pton==1.0.1
prefix: C:\Users\vujovisn\AppData\Local\Continuum\Anaconda3\envs\binder_env

